RSS_FEEDS = [
    # --- Core AI/Tech News (focused) ---
    "https://techcrunch.com/tag/artificial-intelligence/feed/",
    "https://www.theverge.com/artificial-intelligence/rss",
    "https://www.technologyreview.com/feed/",
    "https://www.wired.com/feed/rss",
    "https://www.engadget.com/rss.xml",
    # --- Company & Platform AI blogs ---
    "https://ai.googleblog.com/atom.xml",
    "https://openai.com/blog/rss/",
    "https://blogs.nvidia.com/feed/",
    "https://aws.amazon.com/blogs/machine-learning/feed/",
    "https://www.microsoft.com/en-us/research/feed/",
    "https://huggingface.co/blog/feed.xml",
    "https://stability.ai/blog/rss.xml",
    # --- Research streams ---
    "http://export.arxiv.org/rss/cs.AI",
    "http://export.arxiv.org/rss/cs.CL",
    # --- Community & Dev & Learning ---
    "https://hnrss.org/frontpage?q=ai",
    "https://www.kdnuggets.com/feed",
    "https://towardsdatascience.com/feed",
    "https://www.analyticsvidhya.com/blog/feed/",
    "https://github.blog/feed/",
    "https://opensource.com/feed",
    "https://www.freecodecamp.org/news/rss/",
    "https://blog.coursera.org/feed/",
    "https://realpython.com/atom.xml",
    "https://dev.to/feed",
    "https://hackernoon.com/feed",
    "https://smashingmagazine.com/feed",
    "https://www.sitepoint.com/feed",
    "https://tympanus.net/codrops/feed/",
    "https://stackoverflow.blog/feed/",
    "https://roadmap.sh/blog/rss",
    "https://nesslabs.com/feed",
    "https://blog.trello.com/feed",
    # --- Trend discovery (careful, noisy but useful) ---
    "https://www.producthunt.com/feed",
    "https://topai.tools/feed",
    "https://bensbites.beehiiv.com/feed",
    "https://www.producthunt.com/feed?category=artificial-intelligence",
    "https://hnrss.org/newest?q=AI",
    # --- Arabic / MENA Tech ---
    "https://aitnews.com/feed/",
    "https://www.tech-wd.com/wd/feed/",
    "https://arabhardware.net/feed",
    "https://www.wamda.com/feed",
    "https://www.menabytes.com/feed",
    # --- Engineering/Practitioner voices & open-source project discovery ---
    "https://simonwillison.net/atom/everything/",
    "https://sourceforge.net/blog/feed/",
    "https://mshaban-github-trends-rss.vercel.app/rss",
    "https://deepmind.google/blog/feed/basic/",
    "https://lilianweng.github.io/posts/index.xml",
    "https://karpathy.github.io/feed.xml",
    "https://machinelearningmastery.com/blog/feed/",
    "https://aws.amazon.com/blogs/ai/feed/",
    # --- Productivity & Growth ---
    "https://feeds.feedburner.com/JamesClear",
    "https://tim.blog/feed/",
    "https://www.calnewport.com/blog/feed/",
    "https://www.lifehack.org/feed/",
    "https://www.asianefficiency.com/feed/",
    # --- Free AI Tools & Assets ---
    "https://aiparabellum.com/feed/",
]
